### ISSUE TITLE
Change game name in Discord

### ISSUE THREAD

**Issue by robertmapes** [segalll/DiscordRPCPlugin#1]
Right now it shows "definitely not rl" as the game I am playing. Is there a way to change it to say Rocket League? Thanks.

**Comment by SleepZoff** [comment]
![image](https://user-images.githubusercontent.com/73182143/96600828-6dec5800-1302-11eb-97b2-988713b9f7a3.png)
![image](https://user-images.githubusercontent.com/73182143/96601002-9aa06f80-1302-11eb-9cce-15cd0123b9d0.png)
These two things change mid-game everytime, is there any way to fix this

**Comment by segalll** [comment]
I fixed this at some point years ago, but I don't remember when.
