### ISSUE TITLE
why doesnt this work 

### ISSUE THREAD

**Issue by itzjrdn** [segalll/DiscordRPCPlugin#6]
I installed it but it will not work i am on epic and im trying to load the plugin with the manager but it wont check it for some reason i dont get it is it broken?

**Comment by itzjrdn** [comment]
never mind i changed the dll name

**Comment by Pluzas** [comment]
> never mind i changed the dll name
what did you do exactly ? can you talk me through it ? i'm having the same issues where it doesn't want to check

**Comment by segalll** [comment]
Yeah I should update the description to specify that the DLL name should be changed.
