### ISSUE TITLE
i can't find the dummy discord_game_sdk.dll

### ISSUE THREAD

**Issue by Pluzas** [segalll/DiscordRPCPlugin#7]
i have steam version so when i try to replace the discord_game_sdk.dll i just can't find the dummy in the folder the button sends me to. screenshot of what i find :

![image](https://user-images.githubusercontent.com/62484611/235827032-b3794b92-0076-4672-b969-449ddc44f27b.png)

**Comment by Pluzas** [comment]
never mind i found it in C:\Users\<yourpc>\AppData\Roaming\bakkesmod\bakkesmod\data\DiscordRPCPlugin\dlls

**Comment by segalll** [comment]
I'll update the description to make this easier for new users.
